pipeline:
  identifier: Build_kotlin_playground_1697780728294
  name: Build kotlin-playground
  orgIdentifier: default
  projectIdentifier: KotlinPlayground
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github_OAuth_1697780697693
        repoName: dtkmn/kotlin-playground
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: gradlebuild
                  name: gradle_build
                  spec:
                    image: gradle:latest
                    commands:
                      - gradle build -x test
                  timeout: ""
                  type: Plugin
          platform:
            arch: Amd64
            os: Linux
          runtime:
            spec: {}
            type: Cloud
        type: CI
